### ISSUE TITLE
File concatenation

### ISSUE THREAD

**Issue by baxxtor** [Alkl58/NotEnoughEncodes#2]
A few times now, the encode completed without issue, however file chunk concatenation did not occur with muxing of sound.  I had to use ffmpeg to concatenate the files manually then add audio.

**Comment by baxxtor** [comment]
I found the audio problem. With a input file that has 5.1 audio and I select Enable audio and choose Opus the output will fail.  I have to use Opus 5.1 for audio to work.  Would it be possible to add a third option to convert 5.1 audio input to opus 2 channel audio? Typically, the command in ffmpeg to do this is -ac 2

**Comment by Alkl58** [comment]
> I found the audio problem. With a input file that has 5.1 audio and I select Enable audio and choose Opus the output will fail.

You are right, thats why I implemented the Opus 5.1 option. ffmpeg will crash when using 5.1 Audio with 2.0 Opus.

I added Opus Downmix in this [Commit](https://github.com/Alkl58/NotEnoughEncodes/commit/10c7722e851618e6d240db79a94d4eb0ef147d54)
