### ISSUE TITLE
Muxing of Audio and Video failes if using "resume"

### ISSUE THREAD

**Issue by j-mas** [Alkl58/NotEnoughEncodes#3]
If an encoding operation is resumed after interruption, the muxing of audio and video does not work.
You can only mux the resulting files no_audio.mkv (video) and audio0.mkv (audio in folder AudioEncoded) by hand, e.g. with ffmpeg or mkvtoolnix.

**Comment by Alkl58** [comment]
Does your directory have Spaces in the Path?

Please try the latest [Build](https://ci.appveyor.com/project/Alkl/notenoughencodes/branch/master/artifacts) . I fixed a issue where Spaces in the Path lead to problems in different functions. 

If this didn't helped, please give me more information. (OS, Number of Audiotracks, Path to the directory etc.)

**Comment by j-mas** [comment]
No, no Spaces in the Path.
I tested the last build 1.0.56. Same problem.

I once added a screenshot. Encoding works perfectly, but the muxing of audio and video does not come to an end. (it shows Muxing files and stop) 

I use Windows 10, one audiotrack encoded to AC3, 256 kbit, the path to the directory is C:/NotEnoughEncodes. 

If I encode the same video without interruption (resume) the muxing of video and audio works. 

If you need more information please tell me which ones! Thank you!

![screenshot](https://user-images.githubusercontent.com/43079436/75991526-e11d9700-5ef6-11ea-8b54-1abe0cc8e708.jpg)

**Comment by Alkl58** [comment]
Please try this build.: [NotEnoughEncodes.zip](https://github.com/Alkl58/NotEnoughEncodes/files/4293621/NotEnoughEncodes.zip)
It should create a concat.log file. Please send me then the log file.
What happens if you press "Cancel"?

**Comment by j-mas** [comment]
[concat.log](https://github.com/Alkl58/NotEnoughEncodes/files/4293661/concat.log)
When I press "cancel" I see this message: muxing completed! Elapsed time......
and the new 
[concat.log](https://github.com/Alkl58/NotEnoughEncodes/files/4293680/concat.log)

But it doesen´t finish the muxing. In the temp folder I get the following files:

![screenshot 2](https://user-images.githubusercontent.com/43079436/75996545-4a54d880-5efe-11ea-9191-8786158f1a5f.jpg)

I have an audio file and an noaudio file (video) and have to merge them by myself.

**Comment by Alkl58** [comment]
Thanks for the logfile 👍 

> Number of Audio Tracks: 0

That shouldn't be 0. I will try to find the bug.
Greetings

**Comment by j-mas** [comment]
Because the real audio tracks are not 0.
The encoded audio is available.

Thank you for your efforts!!!

**Comment by Alkl58** [comment]
I think I found the bug, 
Am I right with the assumption that this only happens if you quit the entire program?
I forgot to implement a feature to save the number of audiotracks in the unfinished_job.ini
I will implement a fix.

**Comment by j-mas** [comment]
Yes, you are right. I closed the entire program and then reopened it and continued the encoding.

**Comment by Alkl58** [comment]
Please reopen the issue, if this issue is still occurring for you.
Many Greetings 👍
