### ISSUE TITLE
Crash on resume / resume enhancement.

### ISSUE THREAD

**Issue by Kingdud** [Alkl58/NotEnoughEncodes#4]
I encountered a crash-on-resume issue. It is related to https://github.com/Alkl58/NotEnoughEncodes/blob/865d091999ef7e2609bf139709961e12f43912ce/NotEnoughEncodes/MainWindow.xaml.cs#L623

To recreate the issue:

1. Begin a new encode
2. Cancel the encode before the first chunk(s) finish encoding.
3. Try to resume

The crash is caused because encoded.txt does not get created until after a chunk finishes both passes (I was using 2 pass, but even in one pass, if a job gets canceled before the first chunk finishes being encoded, then it will not create encoded.txt and the user would end up needing to sit through the entire chunking process again, unless they manually create a blank encoded.txt)

----
Enhancements:

1. When encoded.txt is missing, provide the user some way to say "the chunks are all there, just start trying to encode."
2. Write to encoded.txt when, in multi-pass mode, pass 1 completes. In this way, pass 1 does not need to be redone when it was already completed before resume was attempted. Assume any pass-1 log files NOT mentioned in encoded.txt are junk and should be overwritten.

Please and thank you.

**Comment by Alkl58** [comment]
Please try this commit 1ee19e7623121664326c1bb76f8f1d3ff459c349 and tell me if this works for you :)
Build can be found [here](https://ci.appveyor.com/project/Alkl/notenoughencodes/build/artifacts)
Greetings

**Comment by Kingdud** [comment]
I regret to inform you that I have a crash on startup now.

`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	NotEnoughEncodes.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	d7b8868e
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.8.3928.0
  Problem Signature 06:	5d39000b
  Problem Signature 07:	42db
  Problem Signature 08:	0
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
`

is what I get from Windows. Nothing else. I enabled logging (prior to upgrading) and the log doesn't get anything written to it. I'm not sure where/how to look for more info on why the crash is happening.

**Comment by Alkl58** [comment]
Are you on Windows 7?

**Comment by Kingdud** [comment]
Yes. I see my mistake now. I didn't realize you had to manually trigger new windows 7 builds, I thought I was getting one automagically from the appveyor websites.

**Comment by Alkl58** [comment]
Please try this Build: [NotEnoughEncodes.zip](https://github.com/Alkl58/NotEnoughEncodes/files/4293948/NotEnoughEncodes.zip)
I tried it in my Windows 7 VM, but it crashed after I tried to resume. While you test it, I will set up HyperV, because Windows 7 in VirtualBox is too slow.

**Comment by Kingdud** [comment]
I no longer get a crash on launch. Now I get a crash once I actually hit "Start Encoding". It's another filenotfound exception. After some debugging on my end, it's still crashing because it can't find encoded.txt. This in spite of the fact that you now (properly) check if the file exists before trying to use it. ?! WTF! I don't understand.

Based on the log messages, the crash occurs somewhere between lines 640 and 705. Either file.exists() isn't working the way the pages for it describe, or something else weird is going on. I confirmed many times that I was using the new binary you provided and not an older copy.

Sidenote: The new settings for aomenc/ffmpeg paths are nice. They have white backgrounds by default (intended? if so, make the text black?) and do not appear to be persisted into the settings.ini file. Nor does the setting for logging being enabled. Not sure if that's intentional or not.

**Comment by Alkl58** [comment]
Ah...

> I confirmed many times that I was using the new binary you provided and not an older copy.

It accidently send the wrong binary, sry!

Please try this: [NotEnoughEncodes.zip](https://github.com/Alkl58/NotEnoughEncodes/files/4294371/NotEnoughEncodes.zip)

**Comment by Alkl58** [comment]
> Sidenote: The new settings for aomenc/ffmpeg paths are nice. They have white backgrounds by default 

The functions aren't implemented yet. I started implementing them, but then two issue requests appeared on github 😃

**Comment by Alkl58** [comment]
This Fix is working in my Windows 7 VM without issues.
I will Close this Issue. Please reopen / create a new issue, if its not working for you 👍

**Comment by Kingdud** [comment]
Confirmed working. Thanks!
