### ISSUE TITLE
Muxing of Audio and Video failes if using "resume"

### ISSUE THREAD

**Issue by j-mas** [Alkl58/NotEnoughEncodes#5]
Hello Alkl58! 

Unfortunately there is another problem now. The muxing is now completed, but only the first video chunk (2 s) and the entire audio file are muxed. This creates a file with 2 sec video and 60 sec audio!

**Comment by Alkl58** [comment]
I need more information.
What command line did you use? 
I noticed from your last post, that you were using `--limit=100` . Did you also used it for this encode?

**Comment by j-mas** [comment]
Yes. Do you think that´s the problem. Then I will take it away and test.

I thought this command would activate hyperthreading so that all my cores will be used.

**Comment by Alkl58** [comment]
https://github.com/AOMediaCodec/community/wiki/Advanced-Command-Line-Options

--limit | Stop encoding after n input frames
-- | --

Yes, try it without it.

What you are looking for is:

--threads | Max number of threads to use.
-- | --

**Comment by j-mas** [comment]
ok I will try!

**Comment by j-mas** [comment]
You are right. I think this was the problem. Now it works!
My mistake, I'm sorry!!
Thank you for this wonderful GUI and your patience!
And thank you for the link to the Advanced Command Line Options for aom!
I´m searching for this but I didn´t find it!
Best Greetings
j-mas

**Comment by Alkl58** [comment]
No Problem 😄 
Many Greetings 👋
