### ISSUE TITLE
Lower FPS option doesn't work

### ISSUE THREAD

**Issue by NoUserNameForYou** [Alkl58/NotEnoughEncodes#7]
Hello,

 I want to be able to encode files into AV1 with lower frame rates, like 12 FPS. I tried 12000/1000 in the settings but it only made the video slower, without throwing out frames, audio cut off halfway.

Is there any possiblity to do it? I'd like to throw out information or blend frames together, if possible.

**Comment by Alkl58** [comment]
NotEnoughEncodes is discontinued. Please check out [NEAV1E](https://github.com/Alkl58/NotEnoughAV1Encodes)
The Framerate should be matching with the source framerate. You can reencode your video to some lossless format with a lower framerate and then encode it with the GUI.
